project_id = "gdjhducrlrjciinfguwh"

[functions.openrouter-chat]
verify_jwt = false

[functions.huggingface-text]
verify_jwt = false

[functions.huggingface-image]
verify_jwt = false

[functions.huggingface-audio]
verify_jwt = false

[functions.huggingface-video]
verify_jwt = false
